version: '3.9'

services:
  nginx:
    build: ./docker/images/nginx
    container_name: hero-wars_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    volumes:
      - ./dist:/var/www
      - ./docker/images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/images/nginx/sites-available:/etc/nginx/sites-available
  vue:
    build: ./docker/images/vue
    container_name: hero-wars_vue
    tty: true
    working_dir: /app
    volumes:
      - .:/app
