version: '3.9'

services:
  hero-wars-website__vite:
    build: ./docker/images/vue
    container_name: hero-wars-website__vite
    image: hero-wars-website__vite
    entrypoint: /bin/bash
    tty: true
    ports:
      - "8082:8082"
      - "4082:4082"
    working_dir: /app
    volumes:
      - .:/app
