version: '3.9'

services:
  hero-wars-website__node:
    build: ./docker/images/node
    container_name: hero-wars-website__node
    image: hero-wars-website__node
    entrypoint: /bin/bash
    tty: true
    ports:
      - 8082:8082
      - 4082:4082
    working_dir: /app
    volumes:
      - .:/app
