version: '3.9'

services:
  hero-wars-website__vite:
    build: ./docker/images/vue
    container_name: hero-wars-website__vite
    image: hero-wars-website__vite
    entrypoint: /bin/bash
    tty: true
    ports:
      - "8082:8082"
      - "4082:4082"
      - "24678:24678"
    working_dir: /app
    volumes:
      - .:/app

  hero-wars-website__nginx:
    build: ./docker/images/nginx
    container_name: hero-wars-website__nginx
    image: hero-wars-website__nginx
    entrypoint: /bin/bash
    tty: true
    ports:
      - "8085:80"
    working_dir: /var/www
    volumes:
      - ./dist/static:/var/www
      - ./docker/images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/images/nginx/sites-available:/etc/nginx/sites-available
