version: '3.9'

services:
  hero-wars-website__vite:
    build: ./docker/images/vue
    container_name: hero-wars-website__vite
    image: hero-wars-website__vite
    tty: true
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
